services:
  postgres:
    image: postgres:latest
    container_name: lime-task-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: ["postgres", "-c", "search_path=public"]
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql
